// - Generate predictions PDF and auto-download it -
function genPDF(preds, name, email, titleStr) {
  try {
    var jsPDF = window.jspdf.jsPDF;
    var doc   = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    var W = 210, M = 14, y = 20;

    function line(txt, size, bold, rgb) {
      size = size || 10;
      rgb  = rgb  || [200, 210, 230];
      doc.setFontSize(size);
      doc.setFont("helvetica", bold ? "bold" : "normal");
      doc.setTextColor(rgb[0], rgb[1], rgb[2]);
      if (y > 272) { doc.addPage(); y = 20; }
      doc.text(txt, M, y);
      y += size * 0.42 + 2;
    }

    // Background
    doc.setFillColor(8, 15, 28);
    doc.rect(0, 0, W, 297, "F");

    // Header bar
    doc.setFillColor(245, 158, 11);
    doc.rect(0, 0, W, 28, "F");
    doc.setFontSize(16); doc.setFont("helvetica", "bold"); doc.setTextColor(0, 0, 0);
    doc.text("\u26bd  " + titleStr, M, 16);
    doc.setFontSize(9);
    doc.text(name + " \u00b7 " + email + " \u00b7 " + new Date().toLocaleDateString(), M, 24);
    y = 38;

    // Group stage section
    line("GROUP STAGE PREDICTIONS", 11, true, [245, 158, 11]); y += 2;
    GROUPS.forEach(function(g) {
      line("Group " + g + ":  " + TBG[g].join("  \u00b7  "), 9, true, [150, 180, 220]);
      GMS[g].forEach(function(m) {
        var p  = preds.groups && preds.groups[m.id];
        var sc = (p && p.h !== undefined && p.h !== "") ? (p.h + " \u2013 " + p.a) : "? \u2013 ?";
        line("    " + m.home + "  vs  " + m.away + "   \u2192  " + sc, 9, false, [200, 210, 230]);
      });
      y += 1;
    });

    // Knockout section
    y += 4;
    line("KNOCKOUT PREDICTIONS", 11, true, [245, 158, 11]); y += 2;
    var kl = [
      ["r32",   "Round of 32  (32 teams)"],
      ["r16",   "Round of 16  (16 teams)"],
      ["qf",    "Quarter-Finals  (8 teams)"],
      ["sf",    "Semi-Finals  (4 teams)"],
      ["final", "Final  (2 teams)"]
    ];
    var C=cascadeKO(preds.groups,preds.ko||{});
    line("R32 (16 matches): "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("r32")>=0;}).length+"/16 entered",9,false,[200,210,230]);
    line("R16 (8 matches):  "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("r16")>=0;}).length+"/8 entered", 9,false,[200,210,230]);
    line("QF  (4 matches):  "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("qf_")>=0;}).length+"/4 entered", 9,false,[200,210,230]);
    line("SF  (2 matches):  "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("sf_")>=0;}).length+"/2 entered", 9,false,[200,210,230]);
    line("Final:            "+(preds.ko&&preds.ko["final"]?"entered":"not entered"),                                           9,false,[200,210,230]);
    y += 2;
    line("Champion:         " + (C.champion || "(not filled)"), 10, true,  [245, 158, 11]);
    line("3rd Place Winner: " + (C.thirdWin  || "(not filled)"), 10, false, [200, 200, 200]);

    // Footer
    doc.setFontSize(7); doc.setTextColor(80, 90, 110);
    doc.text("Generated by Quiniela Mundial 2026  \u00b7  " + new Date().toLocaleString(), M, 290);

    doc.save(name.replace(/\s+/g, "_") + "_WC2026.pdf");
  } catch(e) {
    console.error("PDF error:", e);
    alert("PDF generation failed: " + e.message);
  }
}

// - Send admin notification email via EmailJS -
async function notifyAdmin(preds, name, email, settings, participants, isUpdate) {
  var ejs = settings.ejs;
  if (!ejs || !ejs.svc || !ejs.tpl_admin || !ejs.key || !settings.adminEmail) return false;

  try {
    // Lazy-load EmailJS
    await new Promise(function(res, rej) {
      if (window.emailjs) { res(); return; }
      var s = document.createElement("script");
      s.src = "https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js";
      s.onload = res; s.onerror = rej;
      document.head.appendChild(s);
    });
    window.emailjs.init(ejs.key);

    // Format group predictions as plain text
    var gLines = GROUPS.map(function(g) {
      return "Group " + g + ": " + GMS[g].map(function(m) {
        var p  = preds.groups && preds.groups[m.id];
        var sc = (p && p.h !== undefined && p.h !== "") ? (p.h + "-" + p.a) : "?-?";
        return m.home + " " + sc + " " + m.away;
      }).join(" | ");
    }).join("\n");

    var kC=cascadeKO(preds.groups,preds.ko||{});
    var koEntries=Object.keys(preds.ko||{}).length;
    var kLines = [
      "KO matches entered: "+koEntries+"/32",
      "Derived champion:   "+(kC.champion||"\u2014"),
      "Derived finalist:   "+((kC.finalTeams&&kC.finalTeams.filter(function(t){return t!==kC.champion;})[0])||"\u2014"),
      "Derived 3rd winner: "+(kC.thirdWin||"\u2014")
    ].join("\n");

    var humanCount = participants.filter(function(p) { return p.id !== "claude_bot"; }).length;

    await window.emailjs.send(ejs.svc, ejs.tpl_admin, {
      to_email:           settings.adminEmail,
      participant_name:   name,
      participant_email:  email,
      is_update:          isUpdate ? "UPDATE" : "NEW",
      total_participants: humanCount,
      group_predictions:  gLines,
      knockout_predictions: kLines,
      submitted_at:       new Date().toLocaleString()
    });

    return true;
  } catch(e) {
    console.error("Admin notify failed:", e);
    return false;
  }
}

// - Lazy-load EmailJS (shared by views) -
function loadEJS() {
  return new Promise(function(res, rej) {
    if (window.emailjs) { res(); return; }
    var s = document.createElement("script");
    s.src = "https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js";
    s.onload = res; s.onerror = rej;
    document.head.appendChild(s);
  });
}

// - Terms & Conditions PDF generator -
async function generateTCPDF(settings, lang) {
  var jsPDF = window.jspdf && window.jspdf.jsPDF;
  if (!jsPDF) { alert("PDF library not loaded. Please try again."); return; }

  var es = lang === "es";
  var cur = settings.currency || "AUD";
  var fee = settings.entryFee || 40;
  var dlRaw = settings.deadline ? new Date(settings.deadline) : null;
  var dlStr = dlRaw ? dlRaw.toLocaleDateString(es?"es-AU":"en-AU",
    {day:"numeric",month:"long",year:"numeric"}) : (es?"10 de junio de 2026":"June 10, 2026");
  var ex10 = fee * 10;

  // All text strings
  var TX = es ? {
    header:   "QUINIELA MUNDIAL 2026 \u2014 SOUTHAMERICAN FOOTBALL FRIENDS SWEEPSTAKE",
    title:    "T\u00e9rminos y Condiciones",
    subtitle: "Copa del Mundo FIFA 2026 \u00b7 EE.UU. \u00b7 Canad\u00e1 \u00b7 M\u00e9xico \u00b7 11 Jun \u2013 19 Jul, 2026",
    s1:"1. Inscripci\u00f3n",
    s1b1:"Cuota de inscripci\u00f3n: "+cur+" "+fee+" por participante.",
    s1b2:"Pago a Julian Enrique Mendez Alvarez \u2014 ING Bank \u00b7 BSB: 923100 / Cuenta: 312595197.",
    s1b3:"Plazo de inscripci\u00f3n: "+dlStr+". No se aceptan inscripciones despu\u00e9s de esta fecha.",
    s1b4:"Todas las predicciones deben ser enviadas a trav\u00e9s del sitio web antes del plazo.",
    s1b5:"Al participar, los participantes aceptan estos t\u00e9rminos y condiciones.",
    s2:"2. Predicciones",
    s2b1:"Los participantes deben predecir el marcador de los 72 partidos de la fase de grupos.",
    s2b2:"Los participantes deben predecir el marcador de los 32 partidos de la fase eliminatoria (desde Ronda de 32 hasta la Final).",
    s2b3:"El cuadro de la Ronda de 32 est\u00e1 determinado por las reglas oficiales de la FIFA 2026 y se calcula autom\u00e1ticamente a partir de las predicciones de grupos.",
    s2b4:"Las predicciones se bloquean en el plazo de inscripci\u00f3n. No se permiten cambios despu\u00e9s.",
    s2b5:"Se puede usar el mismo correo electr\u00f3nico para actualizar predicciones antes del plazo.",
    s3:"3. Puntuaci\u00f3n \u2014 Fase de Grupos (por partido, m\u00e1x 7 pts)",
    s3b1:"Resultado correcto (G/E/P): 3 puntos",
    s3b2:"Goles del Equipo A correctos: 1 punto",
    s3b3:"Goles del Equipo B correctos: 1 punto",
    s3b4:"Diferencia de goles correcta (si el resultado es correcto): 2 puntos",
    s3b5:"Marcador exacto = 7 puntos. Solo resultado correcto = 3 puntos.",
    s4:"4. Puntuaci\u00f3n \u2014 Fase Eliminatoria (por equipo que avanza)",
    s4b1:"Ronda de 32: 1 punto por equipo predicho correctamente",
    s4b2:"Ronda de 16: 2 puntos por equipo",
    s4b3:"Cuartos de Final: 4 puntos por equipo",
    s4b4:"Semifinales: 6 puntos por equipo",
    s4b5:"Partido por el 3er Lugar (equipos en el partido): 8 puntos por equipo",
    s4b6:"Ganador del 3er Lugar: 15 puntos",
    s4b7:"Finalistas (ambos equipos): 10 puntos por equipo",
    s4b8:"Campe\u00f3n del Mundial: 20 puntos",
    s5:"5. Criterios de Desempate",
    s5body:"En caso de empate en puntos totales, se aplican los siguientes criterios en orden:",
    s5b1:"1. Predicci\u00f3n correcta del Campe\u00f3n del Mundial",
    s5b2:"2. Predicci\u00f3n correcta del Subcampe\u00f3n",
    s5b3:"3. Predicci\u00f3n correcta del Ganador del 3er Lugar",
    s5b4:"4. Puntos obtenidos en la Final + Partido por el 3er Lugar",
    s5b5:"5. Puntos obtenidos en las Semifinales",
    s5b6:"6. Si sigue el empate \u2014 los premios se reparten en partes iguales.",
    s6:"6. Distribuci\u00f3n de Premios",
    s6b1:"1er lugar: 50% del pozo de premios",
    s6b2:"2do lugar: 25% del pozo de premios",
    s6b3:"3er lugar: 15% del pozo de premios",
    s6b4:"Gastos de organizaci\u00f3n: 10% del pozo de premios",
    s6b5:"Ejemplo con 10 participantes (pozo de "+cur+" "+ex10+"):",
    s6b6:"Primer lugar: "+cur+" "+Math.floor(ex10*.5),
    s6b7:"Segundo lugar: "+cur+" "+Math.floor(ex10*.25),
    s6b8:"Tercer lugar: "+cur+" "+Math.floor(ex10*.15),
    s6b9:"Gastos de organizacion: "+cur+" "+Math.floor(ex10*.1),
    s7:"7. Resultados y Disputas",
    s7b1:"Se usar\u00e1n los resultados oficiales publicados por la FIFA.",
    s7b2:"Los resultados incluyen el tiempo extra y penales en los partidos eliminatorios.",
    s7b3:"La decisi\u00f3n del organizador en cualquier asunto en disputa es definitiva.",
    s7b4:"Los resultados se actualizar\u00e1n progresivamente en el sitio web.",
    s8:"8. Disposiciones Generales",
    s8b1:"Esta quiniela se organiza con fines de entretenimiento entre amigos.",
    s8b2:"El organizador se reserva el derecho de modificar estos t\u00e9rminos con aviso razonable.",
    s8b3:"Los participantes son responsables de proporcionar un correo electr\u00f3nico v\u00e1lido.",
    s8b4:"Los pagos de premios se realizar\u00e1n dentro de los 14 d\u00edas posteriores a la Final.",
    footer:"Quiniela Mundial 2026  \u00b7  Generado el "+new Date().toLocaleDateString("es-AU"),
    filename:"Quiniela2026_Terminos_y_Condiciones.pdf"
  } : {
    header:   "QUINIELA MUNDIAL 2026 \u2014 SOUTHAMERICAN FOOTBALL FRIENDS SWEEPSTAKE",
    title:    "Terms & Conditions",
    subtitle: "FIFA World Cup 2026 \u00b7 USA \u00b7 Canada \u00b7 Mexico \u00b7 June 11 \u2013 July 19, 2026",
    s1:"1. Entry",
    s1b1:"Entry fee: "+cur+" "+fee+" per participant.",
    s1b2:"Payment to Julian Enrique Mendez Alvarez \u2014 ING Bank \u00b7 BSB: 923100 / Account: 312595197.",
    s1b3:"Registration deadline: "+dlStr+". No entries accepted after this date.",
    s1b4:"All entries must be submitted via the sweepstake website before the deadline.",
    s1b5:"By entering, participants agree to these terms and conditions.",
    s2:"2. Predictions",
    s2b1:"Participants must predict the score of all 72 group stage matches.",
    s2b2:"Participants must predict the score of all 32 knockout matches (Round of 32 through Final).",
    s2b3:"The Round of 32 bracket is determined by the official FIFA 2026 fixture rules and is auto-calculated from group stage predictions.",
    s2b4:"Predictions are locked at the registration deadline. No changes permitted after that time.",
    s2b5:"The same email address can be used to update predictions before the deadline.",
    s3:"3. Scoring \u2014 Group Stage (per match, max 7 pts)",
    s3b1:"Correct result (Win / Draw / Loss): 3 points",
    s3b2:"Correct goals scored by Team A: 1 point",
    s3b3:"Correct goals scored by Team B: 1 point",
    s3b4:"Correct goal difference (if result correct): 2 points",
    s3b5:"Exact scoreline = 7 points. Correct result only = 3 points.",
    s4:"4. Scoring \u2014 Knockout Stage (per team advancing)",
    s4b1:"Round of 32: 1 point per team correctly predicted",
    s4b2:"Round of 16: 2 points per team",
    s4b3:"Quarter-Finals: 4 points per team",
    s4b4:"Semi-Finals: 6 points per team",
    s4b5:"3rd Place Match (teams in match): 8 points per team",
    s4b6:"3rd Place Winner: 15 points",
    s4b7:"Finalists (both teams): 10 points per team",
    s4b8:"World Cup Champion: 20 points",
    s5:"5. Tiebreaker Rules",
    s5body:"In the event of a tie on total points, the following criteria apply in order:",
    s5b1:"1. Correct World Cup Champion prediction",
    s5b2:"2. Correct Runner-up prediction",
    s5b3:"3. Correct 3rd Place winner prediction",
    s5b4:"4. Points earned in the Final + 3rd Place match",
    s5b5:"5. Points earned in the Semi-Finals",
    s5b6:"6. If still tied \u2014 prizes shared equally between tied participants.",
    s6:"6. Prize Distribution",
    s6b1:"1st place: 50% of prize pool",
    s6b2:"2nd place: 25% of prize pool",
    s6b3:"3rd place: 15% of prize pool",
    s6b4:"Admin fee: 10% of prize pool",
    s6b5:"Example with 10 participants ("+cur+" "+ex10+" prize pool):",
    s6b6:"First place: "+cur+" "+Math.floor(ex10*.5),
    s6b7:"Second place: "+cur+" "+Math.floor(ex10*.25),
    s6b8:"Third place: "+cur+" "+Math.floor(ex10*.15),
    s6b9:"Admin fee: "+cur+" "+Math.floor(ex10*.1),
    s7:"7. Results & Disputes",
    s7b1:"Official match results as published by FIFA will be used for scoring.",
    s7b2:"Results include extra time and penalty shootouts for knockout matches.",
    s7b3:"The organiser's decision on any disputed matter is final.",
    s7b4:"Results will be updated on the website progressively as matches are played.",
    s8:"8. General",
    s8b1:"This sweepstake is run for entertainment purposes among friends.",
    s8b2:"The organiser reserves the right to modify these terms with reasonable notice.",
    s8b3:"Participants are responsible for providing a valid email address.",
    s8b4:"Prize payments will be made within 14 days of the World Cup Final.",
    footer:"Quiniela Mundial 2026  \u00b7  Generated "+new Date().toLocaleDateString("en-AU"),
    filename:"Quiniela2026_Terms_and_Conditions.pdf"
  };

  try {
    var doc = new jsPDF({ unit:"mm", format:"a4" });
    var W=210, M=18, cW=W-M*2, y=22;

    function h1(txt){doc.setFont("helvetica","bold");doc.setFontSize(20);doc.setTextColor(30,30,30);doc.text(txt,M,y);y+=9;}
    function h2(txt){doc.setFont("helvetica","bold");doc.setFontSize(13);doc.setTextColor(180,90,0);y+=5;doc.text(txt,M,y);y+=7;}
    function body(txt){doc.setFont("helvetica","normal");doc.setFontSize(10);doc.setTextColor(50,50,50);var l=doc.splitTextToSize(txt,cW);doc.text(l,M,y);y+=l.length*5+2;}
    function bullet(txt){doc.setFont("helvetica","normal");doc.setFontSize(10);doc.setTextColor(50,50,50);var l=doc.splitTextToSize("\u2022  "+txt,cW-4);doc.text(l,M+2,y);y+=l.length*5+1;}
    function rule(){y+=2;doc.setDrawColor(220,220,220);doc.line(M,y,W-M,y);y+=5;}
    function chk(){if(y>265){doc.addPage();y=22;}}

    doc.setFillColor(245,158,11);doc.rect(0,0,W,14,"F");
    doc.setFont("helvetica","bold");doc.setFontSize(11);doc.setTextColor(255,255,255);
    doc.text(TX.header,M,9);y=28;

    h1(TX.title);body(TX.subtitle);rule();
    h2(TX.s1);bullet(TX.s1b1);bullet(TX.s1b2);bullet(TX.s1b3);bullet(TX.s1b4);bullet(TX.s1b5);chk();
    h2(TX.s2);bullet(TX.s2b1);bullet(TX.s2b2);bullet(TX.s2b3);bullet(TX.s2b4);bullet(TX.s2b5);chk();
    h2(TX.s3);bullet(TX.s3b1);bullet(TX.s3b2);bullet(TX.s3b3);bullet(TX.s3b4);bullet(TX.s3b5);chk();
    h2(TX.s4);bullet(TX.s4b1);bullet(TX.s4b2);bullet(TX.s4b3);bullet(TX.s4b4);bullet(TX.s4b5);bullet(TX.s4b6);bullet(TX.s4b7);bullet(TX.s4b8);
    // Force section 5 onto a new page
    doc.addPage(); y=22;
    h2(TX.s5);body(TX.s5body);bullet(TX.s5b1);bullet(TX.s5b2);bullet(TX.s5b3);bullet(TX.s5b4);bullet(TX.s5b5);bullet(TX.s5b6);chk();
    h2(TX.s6);bullet(TX.s6b1);bullet(TX.s6b2);bullet(TX.s6b3);bullet(TX.s6b4);chk();
    body(TX.s6b5);bullet(TX.s6b6);bullet(TX.s6b7);bullet(TX.s6b8);bullet(TX.s6b9);chk();
    h2(TX.s7);bullet(TX.s7b1);bullet(TX.s7b2);bullet(TX.s7b3);bullet(TX.s7b4);chk();
    h2(TX.s8);bullet(TX.s8b1);bullet(TX.s8b2);bullet(TX.s8b3);bullet(TX.s8b4);rule();

    doc.setFont("helvetica","italic");doc.setFontSize(9);doc.setTextColor(150,150,150);
    doc.text(TX.footer,M,285);
    doc.save(TX.filename);
  } catch(e) {
    console.error("T&C PDF error:", e);
    alert("PDF generation failed: " + e.message);
  }
}

// ── Player predictions PDF ───────────────────────────────────────────
async function generatePredsPDF(preds, name, email, lang) {
  var jsPDF = window.jspdf && window.jspdf.jsPDF;
  if (!jsPDF) { alert("PDF library not loaded."); return; }
  var es = lang === "es";
  try {
    var doc = new jsPDF({ unit:"mm", format:"a4" });
    var W=210, M=16, cW=W-M*2, y=20;

    function ln(txt,size,bold,rgb){
      size=size||10; rgb=rgb||[220,230,240];
      doc.setFontSize(size); doc.setFont("helvetica",bold?"bold":"normal");
      doc.setTextColor(rgb[0],rgb[1],rgb[2]);
      if(y>275){doc.addPage();y=20;}
      var lines=doc.splitTextToSize(txt,cW);
      doc.text(lines,M,y); y+=lines.length*(size*0.42+1.2)+1;
    }
    function rule(rgb){
      rgb=rgb||[40,55,80];
      doc.setDrawColor(rgb[0],rgb[1],rgb[2]);
      doc.line(M,y,W-M,y); y+=4;
    }

    // Dark background
    doc.setFillColor(8,15,28);
    doc.rect(0,0,W,297,"F");

    // Header bar
    doc.setFillColor(245,158,11);
    doc.rect(0,0,W,26,"F");
    doc.setFontSize(16);doc.setFont("helvetica","bold");doc.setTextColor(0,0,0);
    doc.text((es?"QUINIELA MUNDIAL 2026":"WORLD CUP 2026 SWEEPSTAKE"),M,11);
    doc.setFontSize(9);doc.setFont("helvetica","normal");
    doc.text((es?"Predicciones de: ":"Predictions by: ")+name+" - "+email,M,19);
    y=34;

    // Group stage
    ln(es?"FASE DE GRUPOS":"GROUP STAGE",12,true,[245,158,11]);
    y+=2; rule([40,60,90]);

    var C=cascadeKO(preds.groups,preds.ko||{});

    GROUPS.forEach(function(g){
      ln("Group "+g+":  "+TBG[g].join("  -  "),9,true,[120,160,210]);
      var mdLabels=["MD1","MD2","MD3"];
      [0,1,2].forEach(function(md){
        GMS[g].slice(md*2,md*2+2).forEach(function(m){
          var pr=preds.groups&&preds.groups[m.id];
          var sc=(pr&&pr.h!==undefined&&pr.h!=="")?pr.h+"-"+pr.a:"?-?";
          var filled=pr&&pr.h!==undefined&&pr.h!=="";
          ln("  "+mdLabels[md]+"  "+m.home+"  vs  "+m.away+"   "+sc,
            9,false,filled?[200,220,240]:[80,100,130]);
        });
      });
      y+=2;
    });

    y+=2; rule([40,60,90]);
    ln(es?"FASE ELIMINATORIA":"KNOCKOUT STAGE",12,true,[245,158,11]);
    y+=2; rule([40,60,90]);

    // KO rounds
    var roundNames=es
      ? ["Ronda de 32","Ronda de 16","Cuartos de Final","Semifinales","Final","Campeon","3er Lugar"]
      : ["Round of 32","Round of 16","Quarter-Finals","Semi-Finals","Final","Champion","3rd Place"];
    var roundKeys=["r32_","r16_","qf_","sf_","final","champion","s3rd"];

    // R32 through SF - show match scores
    var koRounds=[
      {label:roundNames[0],prefix:"r32_",count:16},
      {label:roundNames[1],prefix:"r16_",count:8},
      {label:roundNames[2],prefix:"qf_",count:4},
      {label:roundNames[3],prefix:"sf_",count:2},
    ];

    koRounds.forEach(function(rd){
      ln(rd.label,10,true,[180,140,40]);
      for(var i=0;i<rd.count;i++){
        var fid=rd.prefix+i;
        var r32f=R32_FIXTURES&&R32_FIXTURES.find(function(f){return f.id===fid;});
        var r16f=KO_BRACKET&&KO_BRACKET.r16&&KO_BRACKET.r16.find(function(f){return f.id===fid;});
        var qff=KO_BRACKET&&KO_BRACKET.qf&&KO_BRACKET.qf.find(function(f){return f.id===fid;});
        var sff=KO_BRACKET&&KO_BRACKET.sf&&KO_BRACKET.sf.find(function(f){return f.id===fid;});
        var fixture=r32f||r16f||qff||sff;
        var ko=preds.ko&&preds.ko[fid];
        var sc=ko&&ko.h!==""?ko.h+"-"+ko.a:"?-?";
        var homeTm=C&&C[rd.prefix.replace("_","")+"teams"]&&C[rd.prefix.replace("_","")+"teams"][i*2];
        var awayTm=C&&C[rd.prefix.replace("_","")+"teams"]&&C[rd.prefix.replace("_","")+"teams"][i*2+1];
        var filled=ko&&ko.h!==undefined&&ko.h!=="";
        ln("  M"+(i+1)+":  "+(homeTm||"TBD")+"  "+sc+"  "+(awayTm||"TBD"),
          9,false,filled?[200,220,240]:[80,100,130]);
      }
      y+=1;
    });

    // Final
    var finalko=preds.ko&&preds.ko["final"];
    var finalSc=finalko&&finalko.h!==""?finalko.h+"-"+finalko.a:"?-?";
    ln(roundNames[4],10,true,[180,140,40]);
    ln("  "+(C.finalTeams&&C.finalTeams[0]||"TBD")+"  "+finalSc+"  "+(C.finalTeams&&C.finalTeams[1]||"TBD"),
      9,false,[200,220,240]);
    y+=1;

    // 3rd place
    var s3ko=preds.ko&&preds.ko["s3rd"];
    var s3Sc=s3ko&&s3ko.h!==""?s3ko.h+"-"+s3ko.a:"?-?";
    ln(roundNames[6],10,true,[180,140,40]);
    ln("  "+(C.thirdTeams&&C.thirdTeams[0]||"TBD")+"  "+s3Sc+"  "+(C.thirdTeams&&C.thirdTeams[1]||"TBD"),
      9,false,[200,220,240]);
    y+=2;

    // Champion
    ln(roundNames[5],10,true,[245,158,11]);
    ln("  "+(C.champion||"TBD"),12,true,[245,200,50]);
    y+=2;

    rule([40,60,90]);
    doc.setFontSize(8);doc.setFont("helvetica","italic");doc.setTextColor(60,80,110);
    doc.text("Quiniela Mundial 2026  -  "+new Date().toLocaleString(),M,285);

    doc.save(name.replace(/\s+/g,"_")+"_WC2026_Predictions.pdf");
  } catch(e) {
    console.error("Preds PDF error:",e);
    alert("PDF failed: "+e.message);
  }
}

// ── Player predictions JSON ──────────────────────────────────────────
function downloadPredsJSON(preds, name, email) {
  var data = {
    participant: { name: name, email: email },
    exportedAt: new Date().toISOString(),
    predictions: preds
  };
  var blob = new Blob([JSON.stringify(data, null, 2)], { type:"application/json" });
  var url = URL.createObjectURL(blob);
  var a = document.createElement("a");
  a.href = url;
  a.download = name.replace(/\s+/g,"_")+"_WC2026_Predictions.json";
  a.click();
  URL.revokeObjectURL(url);
}

// ── Per-player score report PDF ──────────────────────────────────────
async function generateReportPDF(participant, results, settings, lang) {
  var jsPDF = window.jspdf && window.jspdf.jsPDF;
  if (!jsPDF) { alert("PDF library not loaded."); return; }
  var es = lang === "es";
  var preds   = participant.preds || {};
  var sc      = settings.scoring  || DEF.scoring;
  var scored  = calcScore(preds, results, sc);
  var rC      = cascadeKO(results.groups, results.ko || {});
  var pC      = cascadeKO(preds.groups,   preds.ko   || {});

  try {
    var doc = new jsPDF({ unit:"mm", format:"a4" });
    var W=210, M=16, cW=W-M*2, y=20;

    // ── helpers ──
    function pg(){ if(y>272){doc.addPage();y=20;} }
    function txt(s,size,bold,r,g,b){
      doc.setFontSize(size||10);
      doc.setFont("helvetica",bold?"bold":"normal");
      doc.setTextColor(r||220,g||230,b||240);
      pg();
      var ls=doc.splitTextToSize(s,cW);
      doc.text(ls,M,y); y+=ls.length*(((size||10)*0.42)+1.5);
    }
    function row(left,center,right,pts,colorR,colorG,colorB){
      pg();
      doc.setFontSize(9); doc.setFont("helvetica","normal");
      doc.setTextColor(colorR||180,colorG||200,colorB||220);
      doc.text(doc.splitTextToSize(left,90),M,y);
      doc.text(center,M+92,y,{align:"center"});
      doc.text(right, M+115,y,{align:"center"});
      doc.setFont("helvetica","bold");
      doc.setTextColor(pts>0?245:120, pts>0?(pts>=6?200:158):130, pts>0?11:140);
      doc.text(pts>0?"+"+pts:(pts===0&&right!=="?"?"-":""),M+cW,y,{align:"right"});
      y+=6;
    }
    function sectionHeader(s){
      y+=3;
      doc.setFillColor(30,45,70); doc.rect(M,y-4,cW,8,"F");
      txt(s,10,true,245,158,11); y+=1;
    }
    function rule(){ doc.setDrawColor(40,60,90); doc.line(M,y,W-M,y); y+=4; }

    // ── Dark background ──
    doc.setFillColor(8,15,28); doc.rect(0,0,W,297,"F");

    // ── Header ──
    doc.setFillColor(245,158,11); doc.rect(0,0,W,28,"F");
    doc.setFontSize(14);doc.setFont("helvetica","bold");doc.setTextColor(0,0,0);
    doc.text(es?"REPORTE DE PUNTUACION":"SCORE REPORT",M,11);
    doc.setFontSize(9);doc.setFont("helvetica","normal");
    doc.text(participant.name+" - "+participant.email,M,17);
    doc.text((es?"Total:":"Total:")+" "+scored.pts+" pts  |  "+
      (es?"Quiniela Mundial 2026":"World Cup 2026 Sweepstake"),M,23);
    y=34;

    // ── Summary boxes ──
    var cats=[
      {l:es?"Fase Grupos":"Group Stage",  v:scored.detail.groups&&scored.detail.groups.earned||0},
      {l:"R32",   v:scored.detail.r32&&scored.detail.r32.earned||0},
      {l:"R16",   v:scored.detail.r16&&scored.detail.r16.earned||0},
      {l:es?"Cuartos":"QF",v:scored.detail.qf&&scored.detail.qf.earned||0},
      {l:es?"Semis":"SF",  v:scored.detail.sf&&scored.detail.sf.earned||0},
      {l:"Final",          v:scored.detail.final&&scored.detail.final.earned||0},
      {l:es?"Campeon":"Champion",v:scored.detail.champion&&scored.detail.champion.earned||0}
    ];
    var bw=24, bx=M;
    cats.forEach(function(c){
      doc.setFillColor(c.v>0?40:20, c.v>0?35:25, c.v>0?15:35);
      doc.roundedRect(bx,y,bw-1,14,2,2,"F");
      doc.setFontSize(7);doc.setFont("helvetica","normal");doc.setTextColor(150,170,190);
      doc.text(c.l,bx+(bw-1)/2,y+5,{align:"center"});
      doc.setFontSize(11);doc.setFont("helvetica","bold");
      doc.setTextColor(c.v>0?245:80,c.v>0?158:90,c.v>0?11:110);
      doc.text(String(c.v),bx+(bw-1)/2,y+11,{align:"center"});
      bx+=bw;
    });
    y+=20; rule();

    // ── Column headers ──
    doc.setFontSize(8);doc.setFont("helvetica","bold");doc.setTextColor(100,130,160);
    doc.text(es?"PARTIDO":"MATCH",M,y);
    doc.text(es?"PRED":"PRED",M+92,y,{align:"center"});
    doc.text(es?"REAL":"ACTUAL",M+115,y,{align:"center"});
    doc.text("PTS",M+cW,y,{align:"right"});
    y+=5; rule();

    // ── Group stage by matchday ──
    GROUPS.forEach(function(g){
      sectionHeader(es?"GRUPO "+g+" - ":"GROUP "+g+" - "+TBG[g].join(" - "));
      [0,1,2].forEach(function(md){
        GMS[g].slice(md*2,md*2+2).forEach(function(m){
          var pred = preds.groups&&preds.groups[m.id];
          var res  = results.groups&&results.groups[m.id];
          var pts  = scoreMatch(pred,res);
          var pSc  = (pred&&pred.h!==''&&pred.h!==undefined)?pred.h+"-"+pred.a:"?";
          var rSc  = (res&&res.h!==''&&res.h!==undefined)?res.h+"-"+res.a:"?";
          var hasRes = rSc!=="?";
          var r=hasRes?(pts>=6?34:pts>=3?140:pts>0?59:180):80;
          var gg=hasRes?(pts>=6?197:pts>=3?160:pts>0?130:80):90;
          var b=hasRes?(pts>=6?94:pts>=3?11:pts>0?46:100):110;
          row("MD"+(md+1)+" "+m.home+" vs "+m.away,pSc,rSc,hasRes?pts:0,r,gg,b);
        });
      });
    });

    y+=3; rule();

    // ── KO stage ──
    sectionHeader(es?"FASE ELIMINATORIA":"KNOCKOUT STAGE");
    y+=2;

    var koSections=[
      {label:"Round of 32",   ids:R32_FIXTURES.map(function(f){return f.id;}), pts:sc.r32||1},
      {label:"Round of 16",   ids:KO_BRACKET.r16.map(function(f){return f.id;}), pts:sc.r16||2},
      {label:"Quarter-Finals",ids:KO_BRACKET.qf.map(function(f){return f.id;}),  pts:sc.qf||4},
      {label:"Semi-Finals",   ids:KO_BRACKET.sf.map(function(f){return f.id;}),  pts:sc.sf||6},
      {label:"Final",         ids:["final"], pts:sc.final||10},
      {label:"3rd Place",     ids:["s3rd"],  pts:sc.thirdMatch||8}
    ];

    koSections.forEach(function(ks){
      txt(ks.label,9,true,245,200,80); y+=1;
      ks.ids.forEach(function(fid){
        var pred=preds.ko&&preds.ko[fid];
        var res =results.ko&&results.ko[fid];
        var pSc=(pred&&pred.h!==''&&pred.h!==undefined)?pred.h+"-"+pred.a:"?";
        var rSc=(res&&res.h!==''&&res.h!==undefined)?res.h+"-"+res.a:"?";
        var matchPts=scoreMatch(pred,res);
        var hasRes=rSc!=="?";

        // Team names from cascade
        var home="TBD", away="TBD";
        var allTeamMaps={
          r32:C&&(pC.r32||{}),r16:(pC.r16||{}),qf:(pC.qf||{}),sf:(pC.sf||{})
        };
        if(rC){
          if(fid==="final"){ home=rC.finalTeams&&rC.finalTeams[0]||"TBD"; away=rC.finalTeams&&rC.finalTeams[1]||"TBD"; }
          else if(fid==="s3rd"){ home=rC.thirdTeams&&rC.thirdTeams[0]||"TBD"; away=rC.thirdTeams&&rC.thirdTeams[1]||"TBD"; }
          else {
            var f32=R32_FIXTURES.find(function(f){return f.id===fid;});
            var f16=KO_BRACKET.r16.find(function(f){return f.id===fid;});
            var fqf=KO_BRACKET.qf.find(function(f){return f.id===fid;});
            var fsf=KO_BRACKET.sf.find(function(f){return f.id===fid;});
            var fx=f32||f16||fqf||fsf;
            if(fx){ home=rC.r32&&rC.r32[fid]&&rC.r32[fid].home||rC.r16&&rC.r16[fid]&&rC.r16[fid].home||rC.qf&&rC.qf[fid]&&rC.qf[fid].home||rC.sf&&rC.sf[fid]&&rC.sf[fid].home||"TBD"; away=rC.r32&&rC.r32[fid]&&rC.r32[fid].away||rC.r16&&rC.r16[fid]&&rC.r16[fid].away||rC.qf&&rC.qf[fid]&&rC.qf[fid].away||rC.sf&&rC.sf[fid]&&rC.sf[fid].away||"TBD"; }
          }
        }
        var r=hasRes?(matchPts>=6?34:matchPts>=3?140:matchPts>0?59:180):80;
        var gg=hasRes?(matchPts>=6?197:matchPts>=3?160:matchPts>0?130:80):90;
        var b2=hasRes?(matchPts>=6?94:matchPts>=3?11:matchPts>0?46:100):110;
        row(home+" vs "+away,pSc,rSc,hasRes?matchPts:0,r,gg,b2);
      });
      y+=2;
    });

    // Champion & 3rd winner
    rule();
    var chHit=pC.champion&&rC.champion&&pC.champion===rC.champion;
    var twHit=pC.thirdWin&&rC.thirdWin&&pC.thirdWin===rC.thirdWin;
    txt(es?"CAMPEON DEL MUNDIAL":"WORLD CUP CHAMPION",9,true,245,200,80);
    row(es?"Prediccion":"Prediction",pC.champion||"?",rC.champion||"?",
      chHit?sc.champion||0:0, chHit?34:180, chHit?197:80, chHit?94:100);
    txt(es?"GANADOR 3er LUGAR":"3RD PLACE WINNER",9,true,245,200,80);
    row(es?"Prediccion":"Prediction",pC.thirdWin||"?",rC.thirdWin||"?",
      twHit?sc.thirdWin||0:0, twHit?34:180, twHit?197:80, twHit?94:100);

    // Footer
    rule();
    doc.setFontSize(8);doc.setFont("helvetica","bold");doc.setTextColor(245,158,11);
    doc.text("TOTAL: "+scored.pts+" pts",M,y);
    doc.setFont("helvetica","italic");doc.setTextColor(60,80,110);
    doc.text("Quiniela Mundial 2026  -  "+new Date().toLocaleString(),W-M,y,{align:"right"});

    doc.save(participant.name.replace(/\s+/g,"_")+"_WC2026_ScoreReport.pdf");
  } catch(e) {
    console.error("Report PDF error:",e);
    alert("Report failed: "+e.message);
  }
}
