// ── Generate predictions PDF and auto-download it ───────────────────
function genPDF(preds, name, email, titleStr) {
  try {
    var jsPDF = window.jspdf.jsPDF;
    var doc   = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    var W = 210, M = 14, y = 20;

    function line(txt, size, bold, rgb) {
      size = size || 10;
      rgb  = rgb  || [200, 210, 230];
      doc.setFontSize(size);
      doc.setFont("helvetica", bold ? "bold" : "normal");
      doc.setTextColor(rgb[0], rgb[1], rgb[2]);
      if (y > 272) { doc.addPage(); y = 20; }
      doc.text(txt, M, y);
      y += size * 0.42 + 2;
    }

    // Background
    doc.setFillColor(8, 15, 28);
    doc.rect(0, 0, W, 297, "F");

    // Header bar
    doc.setFillColor(245, 158, 11);
    doc.rect(0, 0, W, 28, "F");
    doc.setFontSize(16); doc.setFont("helvetica", "bold"); doc.setTextColor(0, 0, 0);
    doc.text("\u26bd  " + titleStr, M, 16);
    doc.setFontSize(9);
    doc.text(name + " \u00b7 " + email + " \u00b7 " + new Date().toLocaleDateString(), M, 24);
    y = 38;

    // Group stage section
    line("GROUP STAGE PREDICTIONS", 11, true, [245, 158, 11]); y += 2;
    GROUPS.forEach(function(g) {
      line("Group " + g + ":  " + TBG[g].join("  \u00b7  "), 9, true, [150, 180, 220]);
      GMS[g].forEach(function(m) {
        var p  = preds.groups && preds.groups[m.id];
        var sc = (p && p.h !== undefined && p.h !== "") ? (p.h + " \u2013 " + p.a) : "? \u2013 ?";
        line("    " + m.home + "  vs  " + m.away + "   \u2192  " + sc, 9, false, [200, 210, 230]);
      });
      y += 1;
    });

    // Knockout section
    y += 4;
    line("KNOCKOUT PREDICTIONS", 11, true, [245, 158, 11]); y += 2;
    var kl = [
      ["r32",   "Round of 32  (32 teams)"],
      ["r16",   "Round of 16  (16 teams)"],
      ["qf",    "Quarter-Finals  (8 teams)"],
      ["sf",    "Semi-Finals  (4 teams)"],
      ["final", "Final  (2 teams)"]
    ];
    var C=cascadeKO(preds.groups,preds.ko||{});
    line("R32 (16 matches): "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("r32")>=0;}).length+"/16 entered",9,false,[200,210,230]);
    line("R16 (8 matches):  "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("r16")>=0;}).length+"/8 entered", 9,false,[200,210,230]);
    line("QF  (4 matches):  "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("qf_")>=0;}).length+"/4 entered", 9,false,[200,210,230]);
    line("SF  (2 matches):  "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("sf_")>=0;}).length+"/2 entered", 9,false,[200,210,230]);
    line("Final:            "+(preds.ko&&preds.ko["final"]?"entered":"not entered"),                                           9,false,[200,210,230]);
    y += 2;
    line("Champion:         " + (C.champion || "(not filled)"), 10, true,  [245, 158, 11]);
    line("3rd Place Winner: " + (C.thirdWin  || "(not filled)"), 10, false, [200, 200, 200]);

    // Footer
    doc.setFontSize(7); doc.setTextColor(80, 90, 110);
    doc.text("Generated by Quiniela Mundial 2026  \u00b7  " + new Date().toLocaleString(), M, 290);

    doc.save(name.replace(/\s+/g, "_") + "_WC2026.pdf");
  } catch(e) {
    console.error("PDF error:", e);
    alert("PDF generation failed: " + e.message);
  }
}

// ── Send admin notification email via EmailJS ────────────────────────
async function notifyAdmin(preds, name, email, settings, participants, isUpdate) {
  var ejs = settings.ejs;
  if (!ejs || !ejs.svc || !ejs.tpl_admin || !ejs.key || !settings.adminEmail) return false;

  try {
    // Lazy-load EmailJS
    await new Promise(function(res, rej) {
      if (window.emailjs) { res(); return; }
      var s = document.createElement("script");
      s.src = "https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js";
      s.onload = res; s.onerror = rej;
      document.head.appendChild(s);
    });
    window.emailjs.init(ejs.key);

    // Format group predictions as plain text
    var gLines = GROUPS.map(function(g) {
      return "Group " + g + ": " + GMS[g].map(function(m) {
        var p  = preds.groups && preds.groups[m.id];
        var sc = (p && p.h !== undefined && p.h !== "") ? (p.h + "-" + p.a) : "?-?";
        return m.home + " " + sc + " " + m.away;
      }).join(" | ");
    }).join("\n");

    var kC=cascadeKO(preds.groups,preds.ko||{});
    var koEntries=Object.keys(preds.ko||{}).length;
    var kLines = [
      "KO matches entered: "+koEntries+"/32",
      "Derived champion:   "+(kC.champion||"\u2014"),
      "Derived finalist:   "+((kC.finalTeams&&kC.finalTeams.filter(function(t){return t!==kC.champion;})[0])||"\u2014"),
      "Derived 3rd winner: "+(kC.thirdWin||"\u2014")
    ].join("\n");

    var humanCount = participants.filter(function(p) { return p.id !== "claude_bot"; }).length;

    await window.emailjs.send(ejs.svc, ejs.tpl_admin, {
      to_email:           settings.adminEmail,
      participant_name:   name,
      participant_email:  email,
      is_update:          isUpdate ? "UPDATE" : "NEW",
      total_participants: humanCount,
      group_predictions:  gLines,
      knockout_predictions: kLines,
      submitted_at:       new Date().toLocaleString()
    });

    return true;
  } catch(e) {
    console.error("Admin notify failed:", e);
    return false;
  }
}

// ── Lazy-load EmailJS (shared by views) ─────────────────────────────
function loadEJS() {
  return new Promise(function(res, rej) {
    if (window.emailjs) { res(); return; }
    var s = document.createElement("script");
    s.src = "https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js";
    s.onload = res; s.onerror = rej;
    document.head.appendChild(s);
  });
}

// ── Terms & Conditions PDF generator ────────────────────────────────
async function generateTCPDF(settings) {
  var jsPDF = window.jspdf && window.jspdf.jsPDF;
  if (!jsPDF) {
    alert("PDF library not loaded. Please try again.");
    return;
  }
  try {
    var doc = new jsPDF({ unit:"mm", format:"a4" });
    var W = 210, M = 18, cW = W - M*2;
    var y = 22;

    // Helper functions
    function h1(txt) {
      doc.setFont("helvetica","bold");
      doc.setFontSize(20);
      doc.setTextColor(30,30,30);
      doc.text(txt, M, y); y += 9;
    }
    function h2(txt) {
      doc.setFont("helvetica","bold");
      doc.setFontSize(13);
      doc.setTextColor(180, 90, 0);
      y += 5;
      doc.text(txt, M, y); y += 7;
    }
    function body(txt) {
      doc.setFont("helvetica","normal");
      doc.setFontSize(10);
      doc.setTextColor(50,50,50);
      var lines = doc.splitTextToSize(txt, cW);
      doc.text(lines, M, y); y += lines.length * 5 + 2;
    }
    function bullet(txt) {
      doc.setFont("helvetica","normal");
      doc.setFontSize(10);
      doc.setTextColor(50,50,50);
      var lines = doc.splitTextToSize("\u2022  " + txt, cW - 4);
      doc.text(lines, M + 2, y); y += lines.length * 5 + 1;
    }
    function rule() {
      y += 2;
      doc.setDrawColor(220,220,220);
      doc.line(M, y, W-M, y);
      y += 5;
    }
    function checkPage() {
      if (y > 265) { doc.addPage(); y = 22; }
    }

    var cur = settings.currency || "AUD";
    var fee = settings.entryFee || 40;
    var deadline = settings.deadline ? new Date(settings.deadline).toLocaleDateString("en-AU", {day:"numeric",month:"long",year:"numeric"}) : "June 10, 2026";
    var total_example = fee * 10;

    // Header
    doc.setFillColor(245, 158, 11);
    doc.rect(0, 0, W, 14, "F");
    doc.setFont("helvetica","bold");
    doc.setFontSize(11);
    doc.setTextColor(255,255,255);
    doc.text("QUINIELA MUNDIAL 2026 \u2014 SOUTHAMERICAN FOOTBALL FRIENDS SWEEPSTAKE", M, 9);
    y = 28;

    h1("Terms & Conditions");
    body("FIFA World Cup 2026 \u00b7 USA \u00b7 Canada \u00b7 Mexico \u00b7 June 11 \u2013 July 19, 2026");
    rule();

    h2("1. Entry");
    bullet("Entry fee: " + cur + " " + fee + " per participant.");
    bullet("Payment to Julian Enrique Mendez Alvarez \u2014 ING Bank \u00b7 BSB: 923100 / Account: 312595197.");
    bullet("Registration deadline: " + deadline + ". No entries accepted after this date.");
    bullet("All entries must be submitted via the sweepstake website before the deadline.");
    bullet("By entering, participants agree to these terms and conditions.");
    checkPage();

    h2("2. Predictions");
    bullet("Participants must predict the score of all 72 group stage matches.");
    bullet("Participants must predict the score of all 32 knockout matches (Round of 32 through Final).");
    bullet("The Round of 32 bracket is determined by the official FIFA 2026 fixture rules and is auto-calculated from group stage predictions.");
    bullet("Predictions are locked at the registration deadline. No changes permitted after that time.");
    bullet("The same email address can be used to update predictions before the deadline.");
    checkPage();

    h2("3. Scoring \u2014 Group Stage (per match, max 7 pts)");
    bullet("Correct result (Win / Draw / Loss): 3 points");
    bullet("Correct goals scored by Team A: 1 point");
    bullet("Correct goals scored by Team B: 1 point");
    bullet("Correct goal difference (if result correct): 2 points");
    bullet("Exact scoreline = 7 points. Correct result only = 3 points.");
    checkPage();

    h2("4. Scoring \u2014 Knockout Stage (per team advancing)");
    bullet("Round of 32: 1 point per team correctly predicted");
    bullet("Round of 16: 2 points per team");
    bullet("Quarter-Finals: 4 points per team");
    bullet("Semi-Finals: 6 points per team");
    bullet("3rd Place Match (teams in match): 8 points per team");
    bullet("3rd Place Winner: 15 points");
    bullet("Finalists (both teams): 10 points per team");
    bullet("World Cup Champion: 20 points");
    checkPage();

    h2("5. Tiebreaker Rules");
    body("In the event of a tie on total points, the following criteria apply in order:");
    bullet("1. Correct World Cup Champion prediction");
    bullet("2. Correct Runner-up prediction");
    bullet("3. Correct 3rd Place winner prediction");
    bullet("4. Points earned in the Final + 3rd Place match");
    bullet("5. Points earned in the Semi-Finals");
    bullet("6. If still tied \u2014 prizes shared equally between tied participants.");
    checkPage();

    h2("6. Prize Distribution");
    var sc = settings.scoring || DEF.scoring;
    bullet("1st place: 50% of prize pool");
    bullet("2nd place: 25% of prize pool");
    bullet("3rd place: 15% of prize pool");
    bullet("Admin fee: 10% of prize pool");
    body("Example with 10 participants: prize pool = " + cur + " " + total_example + " \u2192 1st: " + cur + " " + Math.floor(total_example*0.5) + " \u00b7 2nd: " + cur + " " + Math.floor(total_example*0.25) + " \u00b7 3rd: " + cur + " " + Math.floor(total_example*0.15));
    checkPage();

    h2("7. Results & Disputes");
    bullet("Official match results as published by FIFA will be used for scoring.");
    bullet("Results include extra time and penalty shootouts for knockout matches.");
    bullet("The organiser's decision on any disputed matter is final.");
    bullet("Results will be updated on the website progressively as matches are played.");
    checkPage();

    h2("8. General");
    bullet("This sweepstake is run for entertainment purposes among friends.");
    bullet("The organiser reserves the right to modify these terms with reasonable notice.");
    bullet("Participants are responsible for providing a valid email address.");
    bullet("Prize payments will be made within 14 days of the World Cup Final.");
    rule();

    // Footer
    doc.setFont("helvetica","italic");
    doc.setFontSize(9);
    doc.setTextColor(150,150,150);
    doc.text("Quiniela Mundial 2026  \u00b7  Generated " + new Date().toLocaleDateString(), M, 285);

    doc.save("Quiniela2026_Terms_and_Conditions.pdf");
  } catch(e) {
    console.error("T&C PDF error:", e);
    alert("PDF generation failed: " + e.message);
  }
}
