// ── Generate predictions PDF and auto-download it ───────────────────
function genPDF(preds, name, email, titleStr) {
  try {
    var jsPDF = window.jspdf.jsPDF;
    var doc   = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    var W = 210, M = 14, y = 20;

    function line(txt, size, bold, rgb) {
      size = size || 10;
      rgb  = rgb  || [200, 210, 230];
      doc.setFontSize(size);
      doc.setFont("helvetica", bold ? "bold" : "normal");
      doc.setTextColor(rgb[0], rgb[1], rgb[2]);
      if (y > 272) { doc.addPage(); y = 20; }
      doc.text(txt, M, y);
      y += size * 0.42 + 2;
    }

    // Background
    doc.setFillColor(8, 15, 28);
    doc.rect(0, 0, W, 297, "F");

    // Header bar
    doc.setFillColor(245, 158, 11);
    doc.rect(0, 0, W, 28, "F");
    doc.setFontSize(16); doc.setFont("helvetica", "bold"); doc.setTextColor(0, 0, 0);
    doc.text("\u26bd  " + titleStr, M, 16);
    doc.setFontSize(9);
    doc.text(name + " \u00b7 " + email + " \u00b7 " + new Date().toLocaleDateString(), M, 24);
    y = 38;

    // Group stage section
    line("GROUP STAGE PREDICTIONS", 11, true, [245, 158, 11]); y += 2;
    GROUPS.forEach(function(g) {
      line("Group " + g + ":  " + TBG[g].join("  \u00b7  "), 9, true, [150, 180, 220]);
      GMS[g].forEach(function(m) {
        var p  = preds.groups && preds.groups[m.id];
        var sc = (p && p.h !== undefined && p.h !== "") ? (p.h + " \u2013 " + p.a) : "? \u2013 ?";
        line("    " + m.home + "  vs  " + m.away + "   \u2192  " + sc, 9, false, [200, 210, 230]);
      });
      y += 1;
    });

    // Knockout section
    y += 4;
    line("KNOCKOUT PREDICTIONS", 11, true, [245, 158, 11]); y += 2;
    var kl = [
      ["r32",   "Round of 32  (32 teams)"],
      ["r16",   "Round of 16  (16 teams)"],
      ["qf",    "Quarter-Finals  (8 teams)"],
      ["sf",    "Semi-Finals  (4 teams)"],
      ["final", "Final  (2 teams)"]
    ];
    var C=cascadeKO(preds.groups,preds.ko||{});
    line("R32 (16 matches): "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("r32")>=0;}).length+"/16 entered",9,false,[200,210,230]);
    line("R16 (8 matches):  "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("r16")>=0;}).length+"/8 entered", 9,false,[200,210,230]);
    line("QF  (4 matches):  "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("qf_")>=0;}).length+"/4 entered", 9,false,[200,210,230]);
    line("SF  (2 matches):  "+Object.keys(preds.ko||{}).filter(function(k){return k.indexOf("sf_")>=0;}).length+"/2 entered", 9,false,[200,210,230]);
    line("Final:            "+(preds.ko&&preds.ko["final"]?"entered":"not entered"),                                           9,false,[200,210,230]);
    y += 2;
    line("Champion:         " + (C.champion || "(not filled)"), 10, true,  [245, 158, 11]);
    line("3rd Place Winner: " + (C.thirdWin  || "(not filled)"), 10, false, [200, 200, 200]);

    // Footer
    doc.setFontSize(7); doc.setTextColor(80, 90, 110);
    doc.text("Generated by Quiniela Mundial 2026  \u00b7  " + new Date().toLocaleString(), M, 290);

    doc.save(name.replace(/\s+/g, "_") + "_WC2026.pdf");
  } catch(e) {
    console.error("PDF error:", e);
    alert("PDF generation failed: " + e.message);
  }
}

// ── Send admin notification email via EmailJS ────────────────────────
async function notifyAdmin(preds, name, email, settings, participants, isUpdate) {
  var ejs = settings.ejs;
  if (!ejs || !ejs.svc || !ejs.tpl_admin || !ejs.key || !settings.adminEmail) return false;

  try {
    // Lazy-load EmailJS
    await new Promise(function(res, rej) {
      if (window.emailjs) { res(); return; }
      var s = document.createElement("script");
      s.src = "https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js";
      s.onload = res; s.onerror = rej;
      document.head.appendChild(s);
    });
    window.emailjs.init(ejs.key);

    // Format group predictions as plain text
    var gLines = GROUPS.map(function(g) {
      return "Group " + g + ": " + GMS[g].map(function(m) {
        var p  = preds.groups && preds.groups[m.id];
        var sc = (p && p.h !== undefined && p.h !== "") ? (p.h + "-" + p.a) : "?-?";
        return m.home + " " + sc + " " + m.away;
      }).join(" | ");
    }).join("\n");

    var kC=cascadeKO(preds.groups,preds.ko||{});
    var koEntries=Object.keys(preds.ko||{}).length;
    var kLines = [
      "KO matches entered: "+koEntries+"/32",
      "Derived champion:   "+(kC.champion||"\u2014"),
      "Derived finalist:   "+((kC.finalTeams&&kC.finalTeams.filter(function(t){return t!==kC.champion;})[0])||"\u2014"),
      "Derived 3rd winner: "+(kC.thirdWin||"\u2014")
    ].join("\n");

    var humanCount = participants.filter(function(p) { return p.id !== "claude_bot"; }).length;

    await window.emailjs.send(ejs.svc, ejs.tpl_admin, {
      to_email:           settings.adminEmail,
      participant_name:   name,
      participant_email:  email,
      is_update:          isUpdate ? "UPDATE" : "NEW",
      total_participants: humanCount,
      group_predictions:  gLines,
      knockout_predictions: kLines,
      submitted_at:       new Date().toLocaleString()
    });

    return true;
  } catch(e) {
    console.error("Admin notify failed:", e);
    return false;
  }
}

// ── Lazy-load EmailJS (shared by views) ─────────────────────────────
function loadEJS() {
  return new Promise(function(res, rej) {
    if (window.emailjs) { res(); return; }
    var s = document.createElement("script");
    s.src = "https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js";
    s.onload = res; s.onerror = rej;
    document.head.appendChild(s);
  });
}
